version: 2

sources:
  - name: bronze
    database: "{{ env_var('GCP_PROJECT', 'chicago-taxi-weather-486809') }}"
    schema: chicago_taxi_weather
    tables:
      - name: bronze_taxi_trips_filtered
        description: "Filtered Chicago taxi trips (June–December 2023)"
        columns:
          - name: unique_key
            tests:
              - not_null
              - unique
      - name: bronze_weather_daily
        description: "Daily weather data from Open-Meteo for Chicago"
        columns:
          - name: date
            tests:
              - not_null
              - unique
